### ISSUE TITLE
Marknadsföring genom Facebook-ads

### ISSUE THREAD

**Issue by ghost** [FindH/HH#2]
Vi behöver marknadsföra oss så att fler lägger till sig.

Och jag måste ändå lägga in ngn bild på startsidan så att inte "24hbc" är den bild som kommer upp när ngn share:ar hemsidan på t.ex. facebook.

**Comment by jop3** [comment]
Jag är nog inte riktigt bekväm med att lägga riktiga pengar på reklam innan sidan fungerar bättre än den gör nu. Det är för mycket buggar och skumma saker som stoppar upp för användarna.

Däremot om vi först kan lägga tid på att få klart grundfunktionerna och putsa lite så tycker jag definitivt fb-ads är en bra grej att testa.
