### ISSUE TITLE
Ladda taggar på addHelper innan geo-sökning sker

### ISSUE THREAD

**Issue by ghost** [FindH/HH#3]
Allting fungerar helt ok. Det som är tokigt är bara att "taggarna" laddar Efter att den letat efter var du befinner dig (om besökaren har godkännt detta) . Så vi behöver dels fallback, och dels att taggarna antingen ser bra ut först, eller inte alls visas förrän besökaren har valt/tilldelats plats.

**Comment by jop3** [comment]
Fixat både på addHelper och Index.

Först laddar den default och allt annat, sen kommer frågan om var man befinner sig upp, men man kan strunta i den och köra på default-städerna bara. Godkänner man däremot så visas istället matchande städer mot location.
